"""
Build a self-contained HTML A/B demo for a single surah:

  Plays audio. Shows API verse boundaries vs corrected verse boundaries
  in two parallel tracks. Highlights the verse the player should currently
  be on according to each, plus a horizontal timeline ruler.

Reads:
  data/surah_<N>_tunaiji.json                 (raw API response)
  data/<fix_subdir>/surah_<N>_corrected.json  (default: corrected_v2/)
  data/surah_<N>_verses.json                  (API verses + translations)

Writes:
  demo/surah_<N>_<source_tag>.html

Usage:
  python build_demo.py 1 2 55          # default: whisperx-based fix (v2)
  python build_demo.py --source v1 1   # legacy silencedetect-based fix
"""
import argparse
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).parent
DATA = ROOT / "data"
AUDIO = ROOT / "audio"
DEMO = ROOT / "demo"
DEMO.mkdir(exist_ok=True)

TEMPLATE = """<!doctype html>
<html><head><meta charset="utf-8"/>
<title>Tunaiji subtitle drift A/B demo - Surah __SURAH__</title>
<style>
  body { font-family: -apple-system, system-ui, sans-serif; margin: 2em; background:#fafafa; color:#222; max-width: 1100px; }
  h1 { margin-bottom: 0.2em; }
  .sub { color:#666; margin-bottom:1.5em; }
  .audio-row { display:flex; gap:1em; align-items:center; margin-bottom: 1em; }
  audio { width: 100%; }
  .clock { font-family: monospace; font-size: 1.2em; }
  table.tracks { border-collapse: collapse; width:100%; margin-bottom: 1em; }
  table.tracks th, table.tracks td { border:1px solid #ddd; padding: 6px 10px; vertical-align: top; font-size: 14px; }
  table.tracks th { background:#eef; text-align:left; }
  td.api-active { background:#fde0e0; font-weight:600; }
  td.fix-active { background:#dff5d7; font-weight:600; }
  .delta { font-family: monospace; font-size: 12px; color:#888; }
  .timeline { position:relative; height: 100px; background:#fff; border:1px solid #ddd; border-radius:4px; margin-bottom: 1em; overflow:hidden; }
  .marker { position:absolute; top:0; bottom:0; width:1px; }
  .marker.api { background: rgba(220,40,40,0.55); }
  .marker.fix { background: rgba(40,150,40,0.55); }
  .ruler { position:absolute; bottom:0; left:0; right:0; height: 14px; background:#f6f6f6; border-top:1px solid #eee; font-size:10px; color:#999; }
  .ruler span { position:absolute; top:0; transform: translateX(-50%); padding: 0 2px; }
  .playhead { position:absolute; top:0; bottom:0; width:2px; background: #2080ff; z-index: 5; }
  .legend { font-size: 13px; color:#444; margin-bottom: 1em; }
  .legend .swatch { display:inline-block; width:14px; height:14px; vertical-align:middle; margin-right:4px; border-radius:2px; }
  .verse-key { font-family: monospace; }
  .verse-text-arabic { direction:rtl; font-family: 'Amiri','Scheherazade New',serif; font-size: 22px; }
  .footer { color:#999; font-size: 12px; margin-top: 2em; }
  .stats { font-size: 13px; color:#333; }
  details summary { cursor: pointer; font-weight: 600; padding: 6px 0; }
</style>
</head><body>
<h1>Khalifah Al Tunaiji &mdash; Surah __SURAH__: subtitle drift A/B</h1>
<div class="sub">Compare what English translation would be highlighted using the <b>current Quran.com API timestamps</b> (red) vs <b>__FIX_LABEL__</b> (green). The blue line is the audio playhead.</div>

<div class="legend">
  <span class="swatch" style="background:#fde0e0"></span> API track active &nbsp;
  <span class="swatch" style="background:#dff5d7"></span> Fix track active &nbsp;
  <span class="swatch" style="background:rgba(220,40,40,0.55)"></span> API verse boundary &nbsp;
  <span class="swatch" style="background:rgba(40,150,40,0.55)"></span> Fix verse boundary
</div>

<div class="audio-row">
  <audio id="audio" src="../audio/surah___PAD__.mp3" controls preload="auto"></audio>
  <span class="clock"><span id="now">0.000</span> s</span>
</div>

<div class="timeline" id="timeline"></div>

<table class="tracks">
<thead><tr><th>Verse</th><th>API range (ms)</th><th>Fix range (ms)</th><th>Δ from / Δ to</th><th>English translation</th></tr></thead>
<tbody id="trackbody"></tbody>
</table>

<details>
<summary>Raw stats (boundaries corrected)</summary>
<div class="stats" id="stats"></div>
</details>

<div class="footer">Generated by qrfix. Source: __FIX_SOURCE__.</div>

<script>
const API_DATA = __API_DATA__;
const FIX_DATA = __FIX_DATA__;
const VERSES   = __VERSES__;
const TOTAL_MS = __TOTAL_MS__;

const tbody = document.getElementById('trackbody');
const timeline = document.getElementById('timeline');
const audio = document.getElementById('audio');
const now = document.getElementById('now');
const stats = document.getElementById('stats');

// Build rows
const verseByKey = {};
for (const v of VERSES) verseByKey[v.verse_key] = v;

for (let i = 0; i < API_DATA.length; i++) {
  const a = API_DATA[i], f = FIX_DATA[i];
  const v = verseByKey[a.verse_key] || {};
  const en = (v.translations && v.translations[0] ? v.translations[0].text : '').replace(/<[^>]+>/g,'');
  const dFrom = f.timestamp_from - a.timestamp_from;
  const dTo   = f.timestamp_to - a.timestamp_to;
  const tr = document.createElement('tr');
  tr.dataset.idx = i;
  tr.innerHTML = `
    <td><span class="verse-key">${a.verse_key}</span></td>
    <td><span class="api-cell" id="api-${i}">${a.timestamp_from} &rarr; ${a.timestamp_to}</span></td>
    <td><span class="fix-cell" id="fix-${i}">${f.timestamp_from} &rarr; ${f.timestamp_to}</span></td>
    <td class="delta">${dFrom>=0?'+':''}${dFrom} / ${dTo>=0?'+':''}${dTo} ms</td>
    <td>${en}</td>`;
  tbody.appendChild(tr);
}

// Timeline markers
function addMarker(ms, klass) {
  const m = document.createElement('div');
  m.className = 'marker ' + klass;
  m.style.left = (100 * ms / TOTAL_MS) + '%';
  timeline.appendChild(m);
}
for (let i = 0; i < API_DATA.length - 1; i++) addMarker(API_DATA[i].timestamp_to, 'api');
for (let i = 0; i < FIX_DATA.length - 1; i++) addMarker(FIX_DATA[i].timestamp_to, 'fix');

const ph = document.createElement('div');
ph.className = 'playhead';
ph.style.left = '0%';
timeline.appendChild(ph);

const ruler = document.createElement('div'); ruler.className = 'ruler';
const tickEvery = TOTAL_MS > 60000 ? 10000 : 5000;
for (let t = 0; t <= TOTAL_MS; t += tickEvery) {
  const s = document.createElement('span'); s.style.left = (100*t/TOTAL_MS)+'%';
  s.textContent = (t/1000).toFixed(0) + 's'; ruler.appendChild(s);
}
timeline.appendChild(ruler);

// Stats
let nFixed = 0, maxDelta = 0;
for (let i = 0; i < API_DATA.length; i++) {
  const dTo = FIX_DATA[i].timestamp_to - API_DATA[i].timestamp_to;
  if (dTo !== 0) nFixed++;
  if (Math.abs(dTo) > Math.abs(maxDelta)) maxDelta = dTo;
}
stats.textContent = `Boundaries corrected: ${nFixed} of ${API_DATA.length-1}; max |delta| on timestamp_to: ${maxDelta} ms.`;

function findActiveIdx(ms, arr) {
  for (let i = 0; i < arr.length; i++) {
    if (ms >= arr[i].timestamp_from && ms < arr[i].timestamp_to) return i;
  }
  if (ms >= arr[arr.length-1].timestamp_to) return arr.length - 1;
  return -1;
}

let prevApi = -1, prevFix = -1;
function tick() {
  const ms = audio.currentTime * 1000;
  now.textContent = (ms/1000).toFixed(3);
  ph.style.left = (100 * ms / TOTAL_MS) + '%';
  const aIdx = findActiveIdx(ms, API_DATA);
  const fIdx = findActiveIdx(ms, FIX_DATA);
  if (aIdx !== prevApi) {
    if (prevApi >= 0) document.getElementById('api-'+prevApi).parentElement.classList.remove('api-active');
    if (aIdx >= 0)    document.getElementById('api-'+aIdx).parentElement.classList.add('api-active');
    prevApi = aIdx;
  }
  if (fIdx !== prevFix) {
    if (prevFix >= 0) document.getElementById('fix-'+prevFix).parentElement.classList.remove('fix-active');
    if (fIdx >= 0)    document.getElementById('fix-'+fIdx).parentElement.classList.add('fix-active');
    prevFix = fIdx;
  }
  requestAnimationFrame(tick);
}
audio.addEventListener('play', () => requestAnimationFrame(tick));
audio.addEventListener('seeked', () => requestAnimationFrame(tick));
requestAnimationFrame(tick);
</script>
</body></html>"""


def fetch_verses_with_translation(surah: int):
    """Fetch verses with Saheeh International (id 20) translation if not cached."""
    p = DATA / f"surah_{surah}_verses.json"
    if not p.exists():
        url = f"https://api.quran.com/api/v4/verses/by_chapter/{surah}?translations=20&fields=text_uthmani&words=false&per_page=500"
        subprocess.run(["curl", "-sS", url, "-o", str(p)], check=True)
    return json.loads(p.read_text(encoding="utf-8"))["verses"]


SOURCES = {
    "v2": {
        "subdir": "corrected_v2",
        "label": "WhisperX forced-alignment fix",
        "source": "WhisperX (jonatasgrosman/wav2vec2-large-xlsr-53-arabic), "
                  "boundaries snapped just outside inter-verse silence",
    },
    "v1": {
        "subdir": "corrected",
        "label": "silence-detection-corrected timestamps",
        "source": "silencedetect heuristic (legacy PoC)",
    },
}


def build(surah: int, source: str):
    cfg = SOURCES[source]
    api = json.loads((DATA / f"surah_{surah}_tunaiji.json").read_text(encoding="utf-8"))["audio_file"]
    fix = json.loads((DATA / cfg["subdir"] / f"surah_{surah}_corrected.json").read_text(encoding="utf-8"))["audio_file"]
    verses = fetch_verses_with_translation(surah)
    api_ts = api["timestamps"]
    fix_ts = fix["timestamps"]
    total_ms = max(api_ts[-1]["timestamp_to"], fix_ts[-1]["timestamp_to"])

    html = (TEMPLATE
            .replace("__SURAH__", str(surah))
            .replace("__PAD__", f"{surah:03d}")
            .replace("__API_DATA__", json.dumps(api_ts))
            .replace("__FIX_DATA__", json.dumps(fix_ts))
            .replace("__VERSES__", json.dumps(verses))
            .replace("__TOTAL_MS__", str(total_ms))
            .replace("__FIX_LABEL__", cfg["label"])
            .replace("__FIX_SOURCE__", cfg["source"]))
    out = DEMO / f"surah_{surah}_{source}.html"
    out.write_text(html, encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("surahs", nargs="*", type=int,
                    help="surah numbers to build (default: 1 2 55 78)")
    ap.add_argument("--source", choices=SOURCES.keys(), default="v2",
                    help="which fix to compare against API (default: v2)")
    args = ap.parse_args()
    targets = args.surahs or [1, 2, 55, 78]
    for s in targets:
        build(s, args.source)
